fix: Solana token balance amount crash (#12115)
Error: Number can only safely store up to 53 bits

<!--
Before opening a pull request, please read the [contributing
guidelines](https://github.com/pancakeswap/pancake-frontend/blob/develop/CONTRIBUTING.md)
first
-->

<!-- start pr-codex -->

---

## PR-Codex overview
This PR focuses on enhancing the handling of liquidity and rewards in
the application by introducing `BIG_ZERO` for better consistency and
clarity in calculations, and optimizing some hooks with memoization.

### Detailed summary
- Added `onPresentErrorModal` to `useAddCLLiquidity.tsx`.
- Introduced `UnifiedCurrency` import in `useSwapActionHandlers.ts`.
- Optimized `pos` calculation using `useMemo` in
`InfinityPositionActions.tsx`.
- Replaced `new BN(0)` with `BIG_ZERO` in multiple files for
consistency.
- Updated `getActiveLiquidityFromShape.ts` to use `BIG_ZERO` for
initializing `activeLiquidity`.
- Enhanced `useSolanaTokenBalance` to return `BIG_ZERO` when no mint
address is provided.
- Adjusted `CurrencySearch` to use `BIG_ZERO` for balance handling.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your
question}`

<!-- end pr-codex -->